name: nexora_flashcard_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.6
  flutter_launcher_icons: ^0.14.3
  chat_gpt_sdk: ^3.1.5
  path_provider: ^2.1.1
  flutter_dotenv: ^5.2.1
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  shared_preferences: ^2.0.1
  google_sign_in: ^6.1.0
  flip_card: ^0.6.0
  flutter_slidable: ^0.6.0
  flutter_tts: ^3.8.2
  string_similarity: ^2.1.1
  shake: ^3.0.0
  sound_library: ^1.0.0
  just_audio: ^0.9.36
  auto_size_text: ^3.0.0
  vibration: ^3.1.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
 
  

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/app_fore.png"

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/
    - .env
